export {
  type Backend,
  BLOCK_CHOICES,
  type BlockChoice,
  BUNDLED_GITIGNORE,
  configureBackend,
  copyTemplate,
  HOSTS,
  type Host,
  hostsFor,
  installRecommendedBlocks,
  packageName,
  parseRepo,
  ScaffoldError,
  type ScaffoldOptions,
  scaffold,
  sitePackageJson,
  TEMPLATES,
  type TemplateName,
  withoutRepositoryNotes,
} from "./scaffold.js";
