// Writes files the admin panel needs as text, since Next.js can't import CSS
// or scripts as text: the theme's Tailwind setup, and Tailwind for the browser.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const out = join(dirname(fileURLToPath(import.meta.url)), "../src/generated");
mkdirSync(out, { recursive: true });

const files = {
  "theme-css.ts": require.resolve("@goodfellow/react/theme.css"),
  "tailwind-browser.ts": require.resolve("@tailwindcss/browser"),
};
for (const [name, source] of Object.entries(files)) {
  const text = readFileSync(source, "utf8");
  writeFileSync(
    join(out, name),
    `// Generated by scripts/embed.mjs from ${source.split("node_modules/").pop()}.\nexport default ${JSON.stringify(text)};\n`,
  );
}
