import { createContext, type ReactNode, useContext, useMemo } from "react";

/**
 * Every piece of text the admin panel shows, so it can be reworded or
 * translated. `{name}` placeholders are filled in when the text is used.
 * Puck's own editor text is translated separately, with its `dictionary`.
 */
export const defaultStrings = {
  "app.title": "Site admin",
  "app.viewSite": "View site",
  "nav.pages": "Pages",
  "nav.collections": "Collections",
  "nav.media": "Media",
  "nav.blocks": "Blocks",
  "nav.layout": "Header & footer",
  "nav.settings": "Site settings",

  loading: "Loading…",

  "setup.noBackend":
    "This site's settings don't say where the site is stored, so the admin panel can't open it. A developer needs to add a backend to goodfellow.config.tsx.",
  "signIn.title": "Sign in to edit this site",
  "signIn.intro": "The site is stored on {host}. Sign in with a {host} account that's allowed to change it.",
  "signIn.redirect": "Sign in with {host}",
  "signIn.orToken": "Or sign in with an access token",
  "signIn.token.title": "Sign in with an access token",
  "signIn.token.step1":
    "Create an access token on {host}. This link opens {host} with the right settings already chosen:",
  "signIn.token.create": "Create a token on {host}",
  "signIn.token.createBroad": "Create a broader token instead",
  "signIn.token.createBroadHint":
    "Use this if the site belongs to someone else and the first link doesn't let you choose it. This kind of token can change everything your account can.",
  "signIn.token.chooseSite": "If {host} asks what the token can access, choose this site.",
  "signIn.token.step2": "Copy the token and paste it here:",
  "signIn.token.label": "Access token",
  "signIn.remember": "Stay signed in on this device",
  "signIn.rememberHint": "Leave this off on shared or public computers.",
  "signIn.submit": "Sign in",
  "signIn.checking": "Signing in…",
  "signIn.error.invalid": "That sign-in didn't work. Check that the whole token was copied and that it hasn't expired.",
  "signIn.error.no-access": "That account can't see this site. Make sure the token was given access to it.",
  "signIn.error.cant-publish":
    "That account can see the site but isn't allowed to change it. Ask the site's owner to give it permission.",
  "signIn.error.redirect-failed": "Signing in didn't finish. Try again.",
  "signIn.error.expired": "You were signed out because your sign-in expired. Sign in again to keep editing.",
  "signIn.error.other": "Couldn't reach {host}. Check your connection and try again.",
  "account.signedInAs": "Signed in as {name}",
  "account.signOut": "Sign out",
  "deploy.building": "Updating the live site…",
  "deploy.live": "The live site is up to date",
  "deploy.failed": "The live site couldn't be updated",
  "deploy.details": "Details",
  "loadError.title": "The admin panel couldn't open this site",
  "loadError.contentProblems": "Some of the site's files have problems, so they can't be edited until they're fixed.",
  "loadError.other": "Something went wrong while loading the site. Check your connection and try again.",
  "action.tryAgain": "Try again",
  "action.cancel": "Cancel",
  "action.close": "Close",
  "action.reload": "Reload",
  "action.undo": "Undo",
  "action.redo": "Redo",
  "action.undoHint": "Undo the last change (Ctrl+Z, or ⌘Z on a Mac)",
  "action.redoHint": "Redo what you undid (Ctrl+Shift+Z, or ⇧⌘Z on a Mac)",
  "details.show": "Details",

  "publish.button": "Publish",
  "publish.publishing": "Publishing…",
  "publish.done": "Published.",
  "publish.conflict":
    "Someone else changed the site since you opened this page, so your changes weren't published. Reload to see their changes, then make yours again.",
  "publish.error": "Your changes couldn't be published. Check your connection and try again.",
  "publish.invalid": "Fix the highlighted problems before publishing.",
  "unsaved.confirm": "You have changes that aren't published yet. Leave anyway and lose them?",
  "unsaved.label": "Unpublished changes",

  "pages.title": "Pages",
  "pages.new": "New page",
  "pages.empty": "This site has no pages yet.",
  "pages.column.title": "Title",
  "pages.column.address": "Address",
  "pages.edit": "Edit",
  "pages.move": "Change address",
  "pages.delete": "Delete",
  "pages.view": "View",
  "pages.homeCantDelete": "The home page can't be deleted.",

  "newPage.title": "New page",
  "newPage.pageTitle": "Page title",
  "newPage.address": "Address",
  "newPage.addressHint": "The part of the web address after the site's name, such as /about or /events/picnic.",
  "newPage.create": "Create page",
  "newPage.message": 'Add page "{title}"',

  "movePage.title": "Change the address of {title}",
  "movePage.address": "New address",
  "movePage.updateLinks": "Update menu links to this page",
  "movePage.warning":
    "Links to the old address elsewhere, such as in page text or on other websites, will stop working.",
  "movePage.submit": "Change address",
  "movePage.message": 'Move page "{title}" from {from} to {to}',

  "deletePage.title": "Delete {title}?",
  "deletePage.body": "The page at {path} will be removed from the site. Menu links to it will stop working.",
  "deletePage.submit": "Delete page",
  "deletePage.message": 'Delete page "{title}"',

  "address.invalid": "Use lowercase letters, numbers and hyphens, with / between parts, such as /about-us.",
  "address.reserved": "This address is used by the admin panel. Choose another.",
  "address.taken": "Another page already uses this address.",
  "field.required": "This can't be empty.",

  "editPage.message": 'Update page "{title}"',
  "editPage.notFound": "This page doesn't exist. It may have been moved or deleted.",
  "editPage.backToPages": "Back to pages",

  "layout.header": "Header",
  "layout.footer": "Footer",
  "layout.headerMessage": "Update the header",
  "layout.footerMessage": "Update the footer",

  "collections.title": "Collections",
  "collections.intro":
    "Collections are groups of similar items, such as videos, events or staff. Each collection has its own fields, and can give every item a page that shares one design.",
  "collections.new": "New collection",
  "collections.empty": "There are no collections yet.",
  "collections.column.name": "Name",
  "collections.column.count": "Items",
  "collections.column.address": "Pages",
  "collections.noPages": "No pages of their own",

  "newCollection.title": "New collection",
  "newCollection.name": "Name",
  "newCollection.nameHint": "What the whole collection is called, such as Videos or Events.",
  "newCollection.nameTaken": "Another collection already has a name like this. Choose another.",
  "newCollection.entryName": "One item is called",
  "newCollection.entryNameHint": "Such as Video or Event.",
  "newCollection.pages": "Give each item its own page",
  "newCollection.address": "Address of the pages",
  "newCollection.addressHint": "Each item's page goes inside this address, such as /videos/easter-vigil.",
  "newCollection.create": "Create collection",
  "newCollection.message": 'Add collection "{name}"',

  "collection.tab.entries": "Items",
  "collection.tab.template": "Page design",
  "collection.tab.settings": "Settings",
  "collection.notFound": "This collection doesn't exist. It may have been deleted.",
  "collection.back": "Back to collections",

  "entries.add": "Add {entry}",
  "entries.empty": "There's nothing in {name} yet.",
  "entries.column.title": "Title",
  "entries.column.address": "Address",

  "newEntry.title": "Add {entry}",
  "newEntry.entryTitle": "Title",
  "newEntry.address": "Address",
  "newEntry.addressHint": "The last part of the page's address, as in {example}.",
  "newEntry.message": 'Add {entry} "{title}"',
  "entryName.invalid": "Use lowercase letters, numbers and hyphens only, such as easter-vigil.",
  "entryName.reserved": "This address is used by the admin panel. Choose another.",
  "entryName.taken": "Something else on the site already uses this address.",

  "moveEntry.message": 'Move {entry} "{title}" from {from} to {to}',
  "deleteEntry.body": "{title} will be removed from {name}.",
  "deleteEntry.bodyPage":
    "{title} will be removed from {name}, and its page at {path} from the site. Menu links to it will stop working.",
  "deleteEntry.message": 'Delete {entry} "{title}"',

  "editEntry.message": 'Update {entry} "{title}"',
  "editEntry.notFound": "This item doesn't exist. It may have been renamed or deleted.",
  "editEntry.back": "Back to {name}",
  "editEntry.required": "Fill in {fields} before publishing.",
  "editEntry.noPage":
    "Items in {name} don't have pages of their own. They appear wherever a Collection list block shows {name}.",

  "template.help":
    "Every item's page uses this design. To show an item's information, add an Entry field block, or type a field's name in braces in any text:",
  "template.message": "Update the page design for {name}",
  "template.noPages":
    "Items in {name} don't have pages of their own, so there's no page design. To give them pages, turn that on in Settings.",

  "collectionSettings.markdown": "Store items as Markdown files",
  "collectionSettings.markdownHint":
    "Each item's text is saved as Markdown, a plain-text format that developers can also edit in their own tools. It's edited here as before.",
  "collectionSettings.markdownNeedsText": "To store items as Markdown files, add a formatted-text field first.",
  "collectionSettings.markdownBody": "Field saved as the Markdown text",
  "collectionSettings.markdownConverts": "Every item will be converted when you publish.",
  "collectionSettings.general": "General",
  "collectionSettings.path": "Address of each item's page",
  "collectionSettings.pathHint": "{slug} stands for each item's own address, as in /videos/{slug}.",
  "collectionSettings.pathWarning":
    "Changing this changes the address of every item's page. Links to the old addresses elsewhere will stop working.",
  "collectionSettings.sortField": "Order items by",
  "collectionSettings.sortOrder": "Direction",
  "collectionSettings.ascending": "A to Z, oldest or smallest first",
  "collectionSettings.descending": "Z to A, newest or largest first",
  "collectionSettings.message": "Update the settings for {name}",
  "collectionSettings.addressClash": "With this address, {title} would have the same address as another page.",
  "collectionSettings.delete": "Delete collection",
  "collectionSettings.deleteTitle": "Delete {name}?",
  "collectionSettings.deleteBody":
    "{name} and everything in it ({count} items) will be removed from the site, along with their pages. Collection lists showing it will be empty.",
  "collectionSettings.deleteMessage": 'Delete collection "{name}"',

  "fields.title": "Fields",
  "fields.intro":
    "The information each item has. Every item has a title. A field's kind can't be changed once it's published, but you can add a new field instead.",
  "fields.add": "Add field",
  "fields.label": "Label",
  "fields.type": "Kind of information",
  "fields.required": "Must be filled in",
  "fields.hint": "Help text",
  "fields.options": "Choices",
  "fields.option": "Choice {number}",
  "fields.addOption": "Add choice",
  "fields.optionsRequired": "Add at least one choice.",
  "fields.placeholder": "Show it on the page design with {placeholder}",
  "fields.remove": "Remove field",
  "fields.removed": "Removed fields are also removed from every item when you publish.",
  "fields.newLabel": "New field",
  "fields.type.text": "Short text",
  "fields.type.textarea": "Long text",
  "fields.type.richtext": "Formatted text",
  "fields.type.number": "Number",
  "fields.type.date": "Date",
  "fields.type.link": "Link",
  "fields.type.image": "Image (URL)",
  "fields.type.select": "Choice from a list",

  "demo.banner":
    "This is a demo. Try anything you like: changes are saved in this browser only, and the live site never changes.",
  "demo.published": "Saved in this browser.",
  "demo.startOver": "Start over",
  "demo.startOverTitle": "Start over?",
  "demo.startOverBody": "Everything you've changed in this demo, including uploads, will be undone.",
  "blocks.demo":
    "In this demo you can see which blocks there are, but not add or remove them: a block is added to a real site by updating its code.",

  "markdown.formatted": "Formatted",
  "markdown.source": "Markdown",
  "markdown.sourceOnly":
    "This text uses things the formatted view can't show, such as tables or pictures, so it can only be edited as Markdown.",

  "blocks.title": "Blocks",
  "blocks.intro":
    "Add blocks to the editor, or remove ones you don't use. A change shows in the editor once the site has been updated, usually within a few minutes.",
  "blocks.installed": "Added to this site",
  "blocks.noneInstalled": "No blocks have been added yet. The editor offers the built-in ones.",
  "blocks.loading": "Loading the blocks you can add…",
  "blocks.recommended": "Recommended",
  "blocks.add": "Add",
  "blocks.addLabel": "Add {name}",
  "blocks.added": "Added",
  "blocks.remove": "Remove",
  "blocks.removeLabel": "Remove {name}",
  "blocks.undo": "Undo",
  "blocks.undoAddLabel": "Don't add {name}",
  "blocks.undoRemoveLabel": "Don't remove {name}",
  "blocks.willAdd": "Will be added",
  "blocks.willRemove": "Will be removed",
  "blocks.pendingTitle": "Changes to publish",
  "blocks.pendingAdd": "Add {name}",
  "blocks.pendingRemove": "Remove {name}",
  "blocks.discard": "Discard changes",
  "blocks.publish": "Publish",
  "blocks.publishedNotice":
    "Published. Added blocks will be in the editor's list of blocks, and removed ones gone from it, once the site has been updated.",
  "blocks.addMessage": "Add the {name} block",
  "blocks.removeMessage": "Remove the {name} block",
  "blocks.changeMessage": "Change blocks: {changes}",
  "blocks.addPart": "add {names}",
  "blocks.removePart": "remove {names}",
  "blocks.inUseTitle": "{name} can't be removed yet",
  "blocks.inUse": "{name} is used in: {places}. Take it out of those first, then remove it.",
  "blocks.usedTemplate": "the page design of {name}",
  "blocks.error.record": "The list of blocks added to this site couldn't be read. Tell whoever looks after the site.",
  "blocks.error.unreachable":
    "The blocks you can add couldn't be loaded. Check your internet connection and try again.",
  "blocks.error.invalid": "The list of blocks you can add has a problem, so it couldn't be read. Try again later.",
  "blocks.error.untrusted": "This block comes from somewhere this site doesn't trust, so it can't be added.",
  "blocks.error.not-a-block": "This can't be added to the editor as a block.",
  "blocks.error.already-installed": "{name} has already been added.",
  "blocks.error.name-taken": "The site already has a block with the same name as {name}, so it can't be added.",
  "blocks.error.packages":
    "This block needs software the site doesn't have ({packages}). Ask whoever looks after the site to add it.",
  "blocks.error.unsupported-file":
    "This block includes a file that can't be added from here ({path}). Ask whoever looks after the site to add it.",
  "blocks.error.file-exists":
    "The site already has a different file where this block goes ({path}). Ask whoever looks after the site to add it.",
  "blocks.error.not-installed": "{name} hasn't been added, so there's nothing to remove.",
  "blocks.error.in-use": "{name} is still used on the site. Take it out first, then remove it.",
  "media.title": "Media",
  "media.intro":
    "Images and files for the site. Upload them here, or while editing a page. Large photos are made smaller, and details hidden in photos, such as where they were taken, are removed.",
  "media.upload": "Upload files",
  "media.uploading": "Uploading…",
  "media.drop": "Drop files here to upload them",
  "media.empty": "There are no images or files yet.",
  "media.search": "Find a file",
  "media.noMatches": "No files match.",
  "media.copy": "Copy address",
  "media.copied": "Copied",
  "media.replace": "Replace",
  "media.delete": "Delete",
  "media.uploaded": "Uploaded. Visitors see new files once the live site is updated.",
  "media.uploadMessage": "Add {names}",
  "media.replaceMessage": "Replace {name}",
  "media.deleteMessage": "Delete {name}",
  "media.deleteTitle": "Delete {name}?",
  "media.deleteBody": "{name} will be removed from the site.",
  "media.deleteUsed": "It's used in: {places}. Those places will show a missing image or a broken link.",
  "media.notUsed": "Nothing on the site uses it.",
  "media.error.type":
    "{name} can't be uploaded. The site can use images (JPEG, PNG, GIF, WebP, AVIF and SVG), PDFs, office documents, MP3 audio and MP4 video.",
  "media.error.size":
    "{name} is too large: files can be up to 25 MB. For long videos, upload them to YouTube or Vimeo and link to them instead.",
  "media.error.unreadable":
    "{name} couldn't be read. It may be damaged, or in a format browsers can't open, such as HEIC. Save it as a JPEG and try again.",
  "media.choose": "Choose image",
  "media.chooseFile": "Choose file",
  "media.pickerTitle": "Choose an image",
  "media.pickerTitleFile": "Choose a file",
  "media.pickerEmpty": "Nothing has been uploaded yet. Upload a file to use it here.",
  "media.clear": "Remove",

  "ai.label": "AI",
  "ai.title": "Write with AI",
  "ai.mode.add": "Describe what to add to this page, and AI will write it at the end of the page.",
  "ai.mode.edit": "Describe how to change the selected {block}.",
  "ai.mode.fill": "Describe this {item}, or paste your notes, and AI will fill in its fields.",
  "ai.instruction": "What should it write?",
  "ai.placeholder.add":
    "For example: a section about our Christmas Mass schedule, with a heading, a short welcome and a button to the contact page.",
  "ai.placeholder.edit": "For example: make it shorter and friendlier, or translate it into Spanish.",
  "ai.placeholder.fill": "For example: Fr. Smith's homily from Sunday, about hope. Paste any notes here.",
  "ai.write": "Write it",
  "ai.change": "Change it",
  "ai.fill": "Fill it in",
  "ai.stop": "Stop",
  "ai.working": "Writing…",
  "ai.progress": "Writing… {count} characters so far",
  "ai.done": "Done. Check it over, then publish when you're happy. Undo takes it back.",
  "ai.check":
    "AI can get things wrong, so read what it writes before publishing. It won't make up times, names or prices: it leaves [placeholders] for you to fill in.",
  "ai.needsKey": "To use {service}, add an API key under the AI service settings below, or choose another service.",
  "ai.settings": "AI service: {service}",
  "ai.provider": "AI service",
  "ai.provider.manual": "Copy and paste into a chat app (free)",
  "ai.provider.custom": "Another service (OpenAI-compatible)",
  "ai.noKey": "(free, no key needed)",
  "ai.baseUrl": "Address of the service's API",
  "ai.baseUrlHint": "Such as https://example.org/v1.",
  "ai.key": "API key",
  "ai.keyHint": "Your key stays in this browser and is only ever sent to {service}.",
  "ai.getKey": "Get a key from {service}",
  "ai.remember": "Remember the key on this device",
  "ai.forget": "Forget the key",
  "ai.costHint":
    "{service} may charge the account the key belongs to for each request. Setting a spending limit there is a good idea.",
  "ai.model": "Model",
  "ai.modelHint": "Choose one from the list, or type its name.",
  "ai.model.claude-opus-5-5": "Claude Opus 5.5 (best results)",
  "ai.model.claude-sonnet-5-5": "Claude Sonnet 5.5 (faster, costs less)",
  "ai.model.claude-haiku-4-5": "Claude Haiku 4.5 (fastest, costs least)",
  "ai.manual.step1": "Copy this request into Claude.ai, ChatGPT or another chat app:",
  "ai.manual.copy": "Copy the request",
  "ai.manual.copied": "Copied",
  "ai.manual.step2": "Then paste the chat app's whole answer here:",
  "ai.manual.use": "Use this answer",
  "ai.error.key":
    "{service} didn't accept the API key. Check that it was copied in full, that it hasn't been deleted, and that it can use this model.",
  "ai.error.limit":
    "{service} is limiting requests right now, or the account is out of credit. Wait a minute and try again, or choose another service.",
  "ai.error.network": "Couldn't reach {service}. Check your connection and try again.",
  "ai.error.refused": "{service} declined to write this. Try asking a different way.",
  "ai.error.answer": "The answer couldn't be used. Try again, or try a different model or service.",
  "ai.error.service": "{service} reported a problem. Try again in a moment.",

  "settings.title": "Site settings",
  "settings.tab.general": "General",
  "settings.tab.theme": "Colors & fonts",
  "settings.tab.menus": "Menus",
  "settings.tab.css": "Custom CSS",
  "settings.tab.code": "Code",
  "settings.message": "Update site settings",
  "settings.preview": "Preview of the home page",
  "settings.previewEmpty": "Add a home page to see a preview here.",

  "general.siteTitle": "Site name",
  "general.description": "Description",
  "general.descriptionHint": "Shown by search engines when a page doesn't have its own description.",
  "general.url": "Site address",
  "general.urlHint": "The full public address, such as https://example.org. Used for search engines and link previews.",
  "general.language": "Language code",
  "general.languageHint": "Such as en, es or fr.",
  "general.titleTemplate": "Browser tab title",
  "general.titleTemplateHint": '%s is replaced by the page title, so "%s | My site" shows "About | My site".',
  "general.favicon": "Browser tab icon",
  "general.logo": "Logo",
  "general.logoAlt": "Logo description",
  "general.socialImage": "Image when shared on social media",
  "general.contact": "Contact details",
  "general.contactHint": "Shown wherever a Contact details block is placed, such as the footer.",
  "general.address": "Address",
  "general.phone": "Phone",
  "general.email": "Email",

  "theme.colors": "Colors",
  "theme.fonts": "Fonts",
  "theme.fontsHint": "Choose from Google Fonts. Site default uses each visitor's standard font.",
  "font.default": "Site default",
  "font.defaultHint": "Visitor's standard font",
  "font.search": "Search fonts",
  "font.searchHint": "Type to search Google Fonts, then use the arrow keys and Enter to choose.",
  "font.loading": "Loading fonts…",
  "font.noMatch": "No fonts match “{query}”.",
  "font.category.sans-serif": "Sans serif",
  "font.category.serif": "Serif",
  "font.category.display": "Display",
  "font.category.handwriting": "Handwriting",
  "font.category.monospace": "Monospace",
  "theme.headingFont": "Headings",
  "theme.bodyFont": "Text",
  "theme.radius": "Corner rounding",
  "theme.radiusHint": "Such as 0.5rem, or 0 for square corners.",
  "theme.color.background": "Background",
  "theme.color.foreground": "Text",
  "theme.color.primary": "Main color",
  "theme.color.primaryForeground": "Text on main color",
  "theme.color.secondary": "Second color",
  "theme.color.secondaryForeground": "Text on second color",
  "theme.color.muted": "Subtle background",
  "theme.color.mutedForeground": "Subtle text",
  "theme.color.accent": "Highlight",
  "theme.color.accentForeground": "Text on highlight",
  "theme.color.border": "Borders",
  "theme.default": "Default",
  "theme.pickColor": "Choose a color for {name}",

  "menus.intro": "Menus are lists of links. Show one anywhere with the Menu block, using its name.",
  "menus.empty": "There are no menus yet.",
  "menus.add": "Add menu",
  "menus.newName": "New menu name",
  "menus.nameInvalid": "Use lowercase letters, numbers and hyphens, and a name no other menu uses.",
  "menus.deleteMenu": "Delete menu",
  "menus.addLink": "Add link",
  "menus.addSublink": "Add link below this one",
  "menus.label": "Label",
  "menus.href": "Link to",
  "menus.moveUp": "Move up",
  "menus.moveDown": "Move down",
  "menus.remove": "Remove",
  "menus.newLink": "New link",

  "css.intro": "CSS here applies to every page and overrides the blocks' own styles. Tailwind's @apply works too.",
  "css.label": "Custom CSS",
  "code.intro":
    "Code from services such as analytics or site verification, added to every page of the site. It never runs in the admin panel, so check it on the site once it's published. Paste only code you trust: it can change anything on the site.",
  "code.head": "In the page head",
  "code.headHint": "Script, style, link, meta and noscript tags, such as the ones Google Analytics gives you.",
  "code.body": "At the end of the page",
  "code.bodyHint": "Any HTML, such as a chat widget, added just before the end of every page.",
  "code.error.text":
    'The code in the page head has text outside a tag: "{text}". Only tags such as <script> and <meta> can go there.',
  "code.error.tag": 'A <{tag}> tag can\'t go in the page head. Put it in "At the end of the page" instead.',
  "code.error.unclosed": "A {tag} tag in the page head isn't closed.",
} as const;

export type StringKey = keyof typeof defaultStrings;
export type Strings = Record<StringKey, string>;

const StringsContext = createContext<Strings>(defaultStrings);

export function StringsProvider({ strings, children }: { strings?: Partial<Strings>; children: ReactNode }) {
  const value = useMemo(() => ({ ...defaultStrings, ...strings }), [strings]);
  return <StringsContext.Provider value={value}>{children}</StringsContext.Provider>;
}

export type Translate = (key: StringKey, values?: Record<string, string>) => string;

/** Returns `t(key, values)`, which looks up a string and fills in its `{placeholders}`. */
export function useStrings(): Translate {
  const strings = useContext(StringsContext);
  return (key, values) => strings[key].replace(/\{(\w+)\}/g, (match, name: string) => values?.[name] ?? match);
}
