import { createContext, type ReactNode, useContext, useMemo } from "react";

/**
 * Every piece of text the admin panel shows, so it can be reworded or
 * translated. `{name}` placeholders are filled in when the text is used.
 * Puck's own editor text is translated separately, with its `dictionary`.
 */
export const defaultStrings = {
  "app.title": "Site admin",
  "app.viewSite": "View site",
  "nav.pages": "Pages",
  "nav.collections": "Collections",
  "nav.media": "Media",
  "nav.blocks": "Blocks",
  "nav.layout": "Header & footer",
  "nav.settings": "Site settings",

  loading: "Loading…",

  "setup.noBackend":
    "This site's settings don't say where the site is stored, so the admin panel can't open it. A developer needs to add a backend to goodfellow.config.tsx.",
  "signIn.title": "Sign in to edit this site",
  "signIn.intro": "The site is stored on {host}. Sign in with a {host} account that's allowed to change it.",
  "signIn.redirect": "Sign in with {host}",
  "signIn.orToken": "Or sign in with an access token",
  "signIn.token.title": "Sign in with an access token",
  "signIn.token.step1":
    "Create an access token on {host}. This link opens {host} with the right settings already chosen:",
  "signIn.token.create": "Create a token on {host}",
  "signIn.token.createBroad": "Create a broader token instead",
  "signIn.token.createBroadHint":
    "Use this if the site belongs to someone else and the first link doesn't let you choose it. This kind of token can change everything your account can.",
  "signIn.token.chooseSite": "If {host} asks what the token can access, choose this site.",
  "signIn.token.step2": "Copy the token and paste it here:",
  "signIn.token.label": "Access token",
  "signIn.remember": "Stay signed in on this device",
  "signIn.rememberHint": "Leave this off on shared or public computers.",
  "signIn.submit": "Sign in",
  "signIn.checking": "Signing in…",
  "signIn.error.invalid": "That sign-in didn't work. Check that the whole token was copied and that it hasn't expired.",
  "signIn.error.no-access": "That account can't see this site. Make sure the token was given access to it.",
  "signIn.error.cant-publish":
    "That account can see the site but isn't allowed to change it. Ask the site's owner to give it permission.",
  "signIn.error.redirect-failed": "Signing in didn't finish. Try again.",
  "signIn.error.expired": "You were signed out because your sign-in expired. Sign in again to keep editing.",
  "signIn.error.other": "Couldn't reach {host}. Check your connection and try again.",
  "account.signedInAs": "Signed in as {name}",
  "account.signOut": "Sign out",
  "deploy.building": "Updating the live site…",
  "deploy.live": "The live site is up to date",
  "deploy.failed": "The live site couldn't be updated",
  "build.why": "What went wrong?",
  "build.title": "Why the live site wasn't updated",
  "build.saved":
    "Your changes are published and saved. Visitors see the site as it was until it's rebuilt, which every publish tries again.",
  "build.notStarted":
    "{host} didn't start rebuilding the site. That usually means the account the site belongs to has used up its free build minutes for the month, or its billing on {host} needs attention. One of the site's owners can check the account's billing settings on {host}.",
  "build.install":
    "The site's packages couldn't be installed, so it couldn't be rebuilt. That's sometimes a passing problem with the service the packages come from, so publishing again later may work. If it keeps happening, a developer needs to look at the details.",
  "build.pages":
    "{host} Pages isn't set up for the site, so there's nowhere to put it online. One of the site's owners needs to turn it on in the site's settings on {host}, under Pages.",
  "build.deploy":
    "The site was rebuilt, but {host} couldn't put it online. That's usually a passing problem, so the next publish may work. If it keeps happening, check the site's Pages settings on {host}.",
  "build.host":
    "A problem on {host}'s side stopped the rebuild. That's usually a passing problem, so the next publish may work.",
  "build.content":
    "The site couldn't be rebuilt, because {file} has a problem. Fix it in the admin panel, or put back a version that worked from its version history.",
  "build.contentHistory": "Version history of {file}",
  "build.codeChanged":
    "The site couldn't be rebuilt after its blocks changed. Undo the change under Blocks, by removing what was just added or adding back what was removed, and ask a developer to look at the details.",
  "build.blocks": "Go to Blocks",
  "build.codeFile":
    "The site's code couldn't be rebuilt: there's a problem in {file}. A developer needs to look at the details.",
  "build.code": "The site couldn't be rebuilt. A developer needs to look at the details.",
  "build.unknown": "{host} didn't say why the rebuild failed. Its details may help a developer.",
  "build.hostDetails": "See the details on {host}",
  "loadError.title": "The admin panel couldn't open this site",
  "loadError.contentProblems": "Some of the site's files have problems, so they can't be edited until they're fixed.",
  "loadError.other": "Something went wrong while loading the site. Check your connection and try again.",
  "action.tryAgain": "Try again",
  "action.cancel": "Cancel",
  "action.close": "Close",
  "action.reload": "Reload",
  "action.undo": "Undo",
  "action.redo": "Redo",
  "action.undoHint": "Undo the last change (Ctrl+Z, or ⌘Z on a Mac)",
  "action.redoHint": "Redo what you undid (Ctrl+Shift+Z, or ⇧⌘Z on a Mac)",
  "details.show": "Details",

  "publish.button": "Publish",
  "publish.publishing": "Publishing…",
  "publish.done": "Published.",
  "publish.conflict":
    "Someone else changed the site since you opened this page, so your changes weren't published. Reload to see their changes, then make yours again.",
  "publish.error": "Your changes couldn't be published. Check your connection and try again.",
  "publish.invalid": "Fix the highlighted problems before publishing.",
  "unsaved.confirm": "You have changes that aren't published yet. Leave anyway and lose them?",
  "unsaved.label": "Unpublished changes",

  "pages.title": "Pages",
  "pages.new": "New page",
  "pages.empty": "This site has no pages yet.",
  "pages.column.title": "Title",
  "pages.column.address": "Address",
  "pages.edit": "Edit",
  "pages.move": "Change address",
  "pages.delete": "Delete",
  "pages.view": "View",
  "pages.homeCantDelete": "The home page can't be deleted.",

  "newPage.title": "New page",
  "newPage.pageTitle": "Page title",
  "newPage.address": "Address",
  "newPage.addressHint": "The part of the web address after the site's name, such as /about or /events/picnic.",
  "newPage.create": "Create page",
  "newPage.message": 'Add page "{title}"',

  "movePage.title": "Change the address of {title}",
  "movePage.address": "New address",
  "movePage.updateLinks": "Update menu links to this page",
  "movePage.warning":
    "Links to the old address elsewhere, such as in page text or on other websites, will stop working.",
  "movePage.submit": "Change address",
  "movePage.message": 'Move page "{title}" from {from} to {to}',

  "deletePage.title": "Delete {title}?",
  "deletePage.body": "The page at {path} will be removed from the site. Menu links to it will stop working.",
  "deletePage.submit": "Delete page",
  "deletePage.message": 'Delete page "{title}"',

  "address.invalid": "Use lowercase letters, numbers and hyphens, with / between parts, such as /about-us.",
  "address.reserved": "This address is used by the admin panel. Choose another.",
  "address.taken": "Another page already uses this address.",
  "field.required": "This can't be empty.",

  "editPage.message": 'Update page "{title}"',
  "editPage.notFound": "This page doesn't exist. It may have been moved or deleted.",
  "editPage.backToPages": "Back to pages",

  "versions.button": "Version history",
  "versions.title": "Version history: {title}",
  "versions.back": "Back to editing",
  "versions.intro":
    "Every version that's been published, newest first. Choose one to see it, then restore it to put it back. Something that was moved to a new address starts a new history there.",
  "versions.notFound": "There's no history to show here. It may have been moved or deleted.",
  "versions.local": "Version history is in the published site's admin panel, where you sign in with GitHub or GitLab.",
  "versions.demo": "Version history isn't kept in a demo.",
  "versions.loading": "Loading versions…",
  "versions.loadingVersion": "Loading this version…",
  "versions.error": "The versions couldn't be loaded. Check your connection and try again.",
  "versions.empty": "Nothing has been published here yet.",
  "versions.current": "Current version",
  "versions.by": "{date}, by {author}",
  "versions.more": "Show older versions",
  "versions.preview": "The version from {date}",
  "versions.noPreview": "This item has no page of its own, so there's nothing to preview.",
  "versions.restore": "Restore this version",
  "versions.restoreTitle": "Restore the version from {date}?",
  "versions.restoreBody":
    "{title} goes back to how it was then, and that's published straight away. The current version stays in the history, so you can restore it later.",
  "versions.restoring": "Restoring…",
  "versions.restoreMessage": 'Restore "{title}" to the version from {date}',
  "versions.restored": "Restored the version from {date}.",
  "versions.readError": "This version couldn't be loaded. Check your connection and try again.",
  "versions.unfit":
    "This version can't be restored, because it doesn't fit the site as it is now, for example because the choices for one of its fields have changed.",
  "versions.unknownBlocks":
    "This version can't be restored, because it uses blocks the site doesn't have any more: {blocks}.",

  "layout.header": "Header",
  "layout.footer": "Footer",
  "layout.headerMessage": "Update the header",
  "layout.footerMessage": "Update the footer",

  "collections.title": "Collections",
  "collections.intro":
    "Collections are groups of similar items, such as videos, events or staff. Each collection has its own fields, and can give every item a page that shares one design.",
  "collections.new": "New collection",
  "collections.empty": "There are no collections yet.",
  "collections.column.name": "Name",
  "collections.column.count": "Items",
  "collections.column.address": "Pages",
  "collections.noPages": "No pages of their own",

  "newCollection.title": "New collection",
  "newCollection.kind": "Start with",
  "newCollection.kindBlank": "A title and text",
  "newCollection.kindEvents": "Events",
  "newCollection.kindEventsHint":
    "Each item has a date and time, which can repeat, a place and a summary. Calendar blocks show them, and visitors can add them to their own calendars.",
  "newCollection.eventsName": "Events",
  "newCollection.eventsEntryName": "Event",
  "newCollection.timeZone": "The site's time zone will be set to {zone}. You can change it in Site settings.",
  "newCollection.name": "Name",
  "newCollection.nameHint": "What the whole collection is called, such as Videos or Events.",
  "newCollection.nameTaken": "Another collection already has a name like this. Choose another.",
  "newCollection.entryName": "One item is called",
  "newCollection.entryNameHint": "Such as Video or Event.",
  "newCollection.pages": "Give each item its own page",
  "newCollection.address": "Address of the pages",
  "newCollection.addressHint": "Each item's page goes inside this address, such as /videos/easter-vigil.",
  "newCollection.create": "Create collection",
  "newCollection.message": 'Add collection "{name}"',

  "collection.tab.entries": "Items",
  "collection.tab.template": "Page design",
  "collection.tab.settings": "Settings",
  "collection.notFound": "This collection doesn't exist. It may have been deleted.",
  "collection.back": "Back to collections",

  "entries.add": "Add {entry}",
  "entries.empty": "There's nothing in {name} yet.",
  "entries.column.title": "Title",
  "entries.column.address": "Address",

  "newEntry.title": "Add {entry}",
  "newEntry.entryTitle": "Title",
  "newEntry.address": "Address",
  "newEntry.addressHint": "The last part of the page's address, as in {example}.",
  "newEntry.message": 'Add {entry} "{title}"',
  "entryName.invalid": "Use lowercase letters, numbers and hyphens only, such as easter-vigil.",
  "entryName.reserved": "This address is used by the admin panel. Choose another.",
  "entryName.taken": "Something else on the site already uses this address.",

  "moveEntry.message": 'Move {entry} "{title}" from {from} to {to}',
  "deleteEntry.body": "{title} will be removed from {name}.",
  "deleteEntry.bodyPage":
    "{title} will be removed from {name}, and its page at {path} from the site. Menu links to it will stop working.",
  "deleteEntry.message": 'Delete {entry} "{title}"',

  "editEntry.message": 'Update {entry} "{title}"',
  "editEntry.notFound": "This item doesn't exist. It may have been renamed or deleted.",
  "editEntry.back": "Back to {name}",
  "editEntry.required": "Fill in {fields} before publishing.",
  "editEntry.invalidEvent": "Check {fields}: an event has to end after it starts.",
  "editEntry.noPage":
    "Items in {name} don't have pages of their own. They appear wherever a Collection list block shows {name}.",

  "template.help":
    "Every item's page uses this design. To show an item's information, add an Entry field block, or type a field's name in braces in any text:",
  "template.message": "Update the page design for {name}",
  "template.noPages":
    "Items in {name} don't have pages of their own, so there's no page design. To give them pages, turn that on in Settings.",

  "collectionSettings.markdown": "Store items as Markdown files",
  "collectionSettings.markdownHint":
    "Each item's text is saved as Markdown, a plain-text format that developers can also edit in their own tools. It's edited here as before.",
  "collectionSettings.markdownNeedsText": "To store items as Markdown files, add a formatted-text field first.",
  "collectionSettings.markdownBody": "Field saved as the Markdown text",
  "collectionSettings.markdownConverts": "Every item will be converted when you publish.",
  "collectionSettings.calendar": "Show items in calendars",
  "collectionSettings.calendarHint":
    "Items become events that Calendar blocks show, which visitors can add to their own calendars or subscribe to.",
  "collectionSettings.calendarNeedsDate": 'To show items in calendars, add a "Date and time, for events" field first.',
  "collectionSettings.calendarWhen": "When items happen",
  "collectionSettings.calendarPlace": "Where",
  "collectionSettings.calendarSummary": "Summary",
  "collectionSettings.calendarNone": "None",
  "event.starts": "Starts",
  "event.ends": "Ends (optional)",
  "event.time": "Time",
  "event.allDay": "All day",
  "event.repeats": "Repeats",
  "event.repeat.none": "Doesn't repeat",
  "event.repeat.day": "Daily",
  "event.repeat.week": "Weekly",
  "event.repeat.month": "Monthly",
  "event.repeat.year": "Yearly",
  "event.interval.days": "Every how many days",
  "event.interval.weeks": "Every how many weeks",
  "event.interval.months": "Every how many months",
  "event.interval.years": "Every how many years",
  "event.onDays": "On",
  "event.monthlyOn": "On",
  "event.monthly.date": "Day {day} of the month",
  "event.monthly.weekday": "The {nth} {weekday} of the month",
  "event.monthly.last": "The last {weekday} of the month",
  "event.nth.1": "first",
  "event.nth.2": "second",
  "event.nth.3": "third",
  "event.nth.4": "fourth",
  "event.nth.5": "fifth",
  "event.until": "Until (optional)",
  "event.skip": "Dates it doesn't happen",
  "event.skipDate": "A date it doesn't happen",
  "event.addSkip": "Skip this date",
  "event.next": "Next: {when}",
  "event.when": "{when}",
  "collectionSettings.general": "General",
  "collectionSettings.path": "Address of each item's page",
  "collectionSettings.pathHint": "{slug} stands for each item's own address, as in /videos/{slug}.",
  "collectionSettings.pathWarning":
    "Changing this changes the address of every item's page. Links to the old addresses elsewhere will stop working.",
  "collectionSettings.sortField": "Order items by",
  "collectionSettings.sortOrder": "Direction",
  "collectionSettings.ascending": "A to Z, oldest or smallest first",
  "collectionSettings.descending": "Z to A, newest or largest first",
  "collectionSettings.message": "Update the settings for {name}",
  "collectionSettings.addressClash": "With this address, {title} would have the same address as another page.",
  "collectionSettings.delete": "Delete collection",
  "collectionSettings.deleteTitle": "Delete {name}?",
  "collectionSettings.deleteBody":
    "{name} and everything in it ({count} items) will be removed from the site, along with their pages. Collection lists showing it will be empty.",
  "collectionSettings.deleteMessage": 'Delete collection "{name}"',

  "fields.title": "Fields",
  "fields.intro":
    "The information each item has. Every item has a title. A field's kind can't be changed once it's published, but you can add a new field instead.",
  "fields.add": "Add field",
  "fields.label": "Label",
  "fields.type": "Kind of information",
  "fields.required": "Must be filled in",
  "fields.hint": "Help text",
  "fields.options": "Choices",
  "fields.option": "Choice {number}",
  "fields.addOption": "Add choice",
  "fields.optionsRequired": "Add at least one choice.",
  "fields.placeholder": "Show it on the page design with {placeholder}",
  "fields.remove": "Remove field",
  "fields.removed": "Removed fields are also removed from every item when you publish.",
  "fields.newLabel": "New field",
  "fields.type.text": "Short text",
  "fields.type.textarea": "Long text",
  "fields.type.richtext": "Formatted text",
  "fields.type.number": "Number",
  "fields.type.date": "Date",
  "fields.type.event": "Date and time, for events",
  "fields.type.link": "Link",
  "fields.type.image": "Image (URL)",
  "fields.type.select": "Choice from a list",
  "fields.type.tags": "Tags (any number of choices from a list)",

  "demo.banner":
    "This is a demo. Try anything you like: your changes show here in the admin panel and are saved in this browser only. The site itself never changes.",
  "demo.published": "Saved in this browser. The site itself doesn't change in a demo.",
  "demo.startOver": "Start over",
  "demo.startOverTitle": "Start over?",
  "demo.startOverBody": "Everything you've changed in this demo, including uploads, will be undone.",
  "blocks.demo":
    "In this demo you can see which blocks there are, but not add or remove them: a block is added to a real site by updating its code.",

  "markdown.formatted": "Formatted",
  "markdown.source": "Markdown",
  "markdown.sourceOnly":
    "This text uses things the formatted view can't show, such as tables or pictures, so it can only be edited as Markdown.",

  "blocks.title": "Blocks",
  "blocks.intro":
    "Add blocks to the editor, or remove ones you don't use. A change shows in the editor once the site has been updated, usually within a few minutes.",
  "blocks.installed": "Added to this site",
  "blocks.noneInstalled": "No blocks have been added yet. The editor offers the built-in ones.",
  "blocks.loading": "Loading the blocks you can add…",
  "blocks.recommended": "Recommended",
  "blocks.add": "Add",
  "blocks.addLabel": "Add {name}",
  "blocks.added": "Added",
  "blocks.remove": "Remove",
  "blocks.removeLabel": "Remove {name}",
  "blocks.undo": "Undo",
  "blocks.undoAddLabel": "Don't add {name}",
  "blocks.undoRemoveLabel": "Don't remove {name}",
  "blocks.willAdd": "Will be added",
  "blocks.willRemove": "Will be removed",
  "blocks.pendingTitle": "Changes to publish",
  "blocks.pendingAdd": "Add {name}",
  "blocks.pendingRemove": "Remove {name}",
  "blocks.discard": "Discard changes",
  "blocks.publish": "Publish",
  "blocks.publishedNotice":
    "Published. Added blocks will be in the editor's list of blocks, and removed ones gone from it, once the site has been updated.",
  "blocks.addMessage": "Add the {name} block",
  "blocks.removeMessage": "Remove the {name} block",
  "blocks.changeMessage": "Change blocks: {changes}",
  "blocks.addPart": "add {names}",
  "blocks.removePart": "remove {names}",
  "blocks.inUseTitle": "{name} can't be removed yet",
  "blocks.inUse": "{name} is used in: {places}. Take it out of those first, then remove it.",
  "blocks.usedTemplate": "the page design of {name}",
  "blocks.error.record": "The list of blocks added to this site couldn't be read. Tell whoever looks after the site.",
  "blocks.error.unreachable":
    "The blocks you can add couldn't be loaded. Check your internet connection and try again.",
  "blocks.error.invalid": "The list of blocks you can add has a problem, so it couldn't be read. Try again later.",
  "blocks.error.untrusted": "This block comes from somewhere this site doesn't trust, so it can't be added.",
  "blocks.error.not-a-block": "This can't be added to the editor as a block.",
  "blocks.error.already-installed": "{name} has already been added.",
  "blocks.error.name-taken": "The site already has a block with the same name as {name}, so it can't be added.",
  "blocks.error.packages":
    "This block needs software the site doesn't have ({packages}). Ask whoever looks after the site to add it.",
  "blocks.error.unsupported-file":
    "This block includes a file that can't be added from here ({path}). Ask whoever looks after the site to add it.",
  "blocks.error.file-exists":
    "The site already has a different file where this block goes ({path}). Ask whoever looks after the site to add it.",
  "blocks.error.not-installed": "{name} hasn't been added, so there's nothing to remove.",
  "blocks.error.in-use": "{name} is still used on the site. Take it out first, then remove it.",
  "media.title": "Media",
  "media.intro":
    "Images and files for the site. Upload them here, or while editing a page. Large photos are made smaller, and details hidden in photos, such as where they were taken, are removed.",
  "media.upload": "Upload files",
  "media.uploading": "Uploading…",
  "media.drop": "Drop files here to upload them",
  "media.empty": "There are no images or files yet.",
  "media.search": "Find a file",
  "media.noMatches": "No files match.",
  "media.copy": "Copy address",
  "media.copied": "Copied",
  "media.replace": "Replace",
  "media.delete": "Delete",
  "media.uploaded": "Uploaded. Visitors see new files once the live site is updated.",
  "media.uploadMessage": "Add {names}",
  "media.replaceMessage": "Replace {name}",
  "media.deleteMessage": "Delete {name}",
  "media.deleteTitle": "Delete {name}?",
  "media.deleteBody": "{name} will be removed from the site.",
  "media.deleteUsed": "It's used in: {places}. Those places will show a missing image or a broken link.",
  "media.notUsed": "Nothing on the site uses it.",
  "media.error.type":
    "{name} can't be uploaded. The site can use images (JPEG, PNG, GIF, WebP, AVIF and SVG), PDFs, office documents, MP3 audio and MP4 video.",
  "media.error.size":
    "{name} is too large: files can be up to 25 MB. For long videos, upload them to YouTube or Vimeo and link to them instead.",
  "media.error.unreadable":
    "{name} couldn't be read. It may be damaged, or in a format browsers can't open, such as HEIC. Save it as a JPEG and try again.",
  "media.choose": "Choose image",
  "media.chooseFile": "Choose file",
  "media.pickerTitle": "Choose an image",
  "media.pickerTitleFile": "Choose a file",
  "media.pickerEmpty": "Nothing has been uploaded yet. Upload a file to use it here.",
  "media.clear": "Remove",

  "ai.label": "AI",
  "ai.title": "Write with AI",
  "ai.mode.add": "Describe what to add to this page, and AI will write it at the end of the page.",
  "ai.mode.edit": "Describe how to change the selected {block}.",
  "ai.mode.fill": "Describe this {item}, or paste your notes, and AI will fill in its fields.",
  "ai.instruction": "What should it write?",
  "ai.placeholder.add":
    "For example: a section about our Christmas Mass schedule, with a heading, a short welcome and a button to the contact page.",
  "ai.placeholder.edit": "For example: make it shorter and friendlier, or translate it into Spanish.",
  "ai.placeholder.fill": "For example: Fr. Smith's homily from Sunday, about hope. Paste any notes here.",
  "ai.write": "Write it",
  "ai.change": "Change it",
  "ai.fill": "Fill it in",
  "ai.stop": "Stop",
  "ai.working": "Writing…",
  "ai.progress": "Writing… {count} characters so far",
  "ai.done": "Done. Check it over, then publish when you're happy. Undo takes it back.",
  "ai.check":
    "AI can get things wrong, so read what it writes before publishing. It won't make up times, names or prices: it leaves [placeholders] for you to fill in.",
  "ai.needsKey": "To use {service}, add an API key under the AI service settings below, or choose another service.",
  "ai.settings": "AI service: {service}",
  "ai.provider": "AI service",
  "ai.provider.manual": "Copy and paste into a chat app (free)",
  "ai.provider.custom": "Another service (OpenAI-compatible)",
  "ai.noKey": "(free, no key needed)",
  "ai.baseUrl": "Address of the service's API",
  "ai.baseUrlHint": "Such as https://example.org/v1.",
  "ai.key": "API key",
  "ai.keyHint": "Your key stays in this browser and is only ever sent to {service}.",
  "ai.getKey": "Get a key from {service}",
  "ai.remember": "Remember the key on this device",
  "ai.forget": "Forget the key",
  "ai.costHint":
    "{service} may charge the account the key belongs to for each request. Setting a spending limit there is a good idea.",
  "ai.model": "Model",
  "ai.modelHint": "Choose one from the list, or type its name.",
  "ai.model.claude-opus-5-5": "Claude Opus 5.5 (best results)",
  "ai.model.claude-sonnet-5-5": "Claude Sonnet 5.5 (faster, costs less)",
  "ai.model.claude-haiku-4-5": "Claude Haiku 4.5 (fastest, costs least)",
  "ai.manual.step1": "Copy this request into Claude.ai, ChatGPT or another chat app:",
  "ai.manual.copy": "Copy the request",
  "ai.manual.copied": "Copied",
  "ai.manual.step2": "Then paste the chat app's whole answer here:",
  "ai.manual.use": "Use this answer",
  "ai.error.key":
    "{service} didn't accept the API key. Check that it was copied in full, that it hasn't been deleted, and that it can use this model.",
  "ai.error.limit":
    "{service} is limiting requests right now, or the account is out of credit. Wait a minute and try again, or choose another service.",
  "ai.error.network": "Couldn't reach {service}. Check your connection and try again.",
  "ai.error.refused": "{service} declined to write this. Try asking a different way.",
  "ai.error.answer": "The answer couldn't be used. Try again, or try a different model or service.",
  "ai.error.service": "{service} reported a problem. Try again in a moment.",

  "settings.title": "Site settings",
  "appearance.choice": "Colors of the admin panel",
  "appearance.system": "Match my computer",
  "appearance.light": "Light",
  "appearance.dark": "Dark",
  "settings.tab.general": "General",
  "settings.tab.theme": "Colors & fonts",
  "settings.tab.menus": "Menus",
  "settings.tab.css": "Custom CSS",
  "settings.tab.code": "Code",
  "settings.tab.domain": "Domain",
  "settings.message": "Update site settings",
  "settings.preview": "Preview of the home page",
  "settings.previewEmpty": "Add a home page to see a preview here.",

  "domain.intro": "Connect a domain you own, such as example.org, so the site is at that address.",
  "domain.current": "The site is at {address} now.",
  "domain.connected": "Connected to {domain}.",
  "domain.signIn":
    "Editors sign in by going to {host} and coming back here. Add {address} to the redirect URIs of the application they sign in with on {host}, or signing in will stop working once the site moves.",
  "domain.local": "Domains are connected in the published site's admin panel, where you sign in with GitHub or GitLab.",
  "domain.demo": "Domains can't be connected in a demo.",
  "domain.loading": "Finding where the site is published…",
  "domain.elsewhere": "This site isn't published with {host} Pages, so its domain is connected where it is published.",
  "domain.elsewhere.vercel":
    "On Vercel: open the site's project, go to Settings → Domains and add the domain. Vercel shows the records to add at your registrar. Once the site works at its new address, put the address in General → Site address and publish.",
  "domain.field": "Domain",
  "domain.fieldHint":
    "Such as example.org or www.example.org. Buy one first from a registrar, such as Cloudflare, Namecheap or Porkbun. For example.org, www.example.org works too.",
  "domain.invalid": "That isn't a domain. Type it like example.org.",
  "domain.warning":
    "Once it's connected, the site's current address sends visitors to the new one, which works only once the records are in place. Have your registrar's DNS settings open, and add the records straight away.",
  "domain.connect": "Connect domain",
  "domain.connecting": "Connecting…",
  "domain.message": "Use the domain {domain}",
  "domain.records.title": "1. Add these records at your registrar",
  "domain.records.hint":
    "Your registrar is where you bought the domain. In its DNS settings, add each record below. Delete any other A, AAAA or CNAME records with the same names, such as a page the registrar shows on new domains.",
  "domain.records.type": "Type",
  "domain.records.name": "Name",
  "domain.records.value": "Value",
  "domain.records.state": "Found",
  "domain.records.ok": "In place",
  "domain.records.missing": "Not there yet",
  "domain.records.wrong": "Something else is there: {found}",
  "domain.records.optional": "optional",
  "domain.purpose.site": "Points the domain at the site.",
  "domain.purpose.verification": "Proves to {host} that the domain is yours. Leave it in place.",
  "domain.purpose.www": "Sends www. to the site too.",
  "domain.guides": "How to add records at:",
  "domain.cloudflare":
    "On Cloudflare, set each record's proxy status to DNS only, or {host} can't set up HTTPS for the domain.",
  "domain.host.title": "2. {host} checks the domain and sets up HTTPS",
  "domain.host.unverified": "Waiting for {host} to find the record that proves the domain is yours.",
  "domain.host.pending":
    "Waiting for the HTTPS certificate, which {host} asks for once the records are in place. It can take up to a day.",
  "domain.host.ready": "The HTTPS certificate is ready.",
  "domain.host.failed":
    "The HTTPS certificate couldn't be set up. Check the records, then remove the domain and connect it again.",
  "domain.site.title": "3. The site opens at {address}",
  "domain.site.waiting": "Not yet. New records can take from a few minutes to a day to reach everyone.",
  "domain.site.ok": "It does.",
  "domain.secure": "Send everyone to {address}",
  "domain.secureHint": "Visitors always get the secure address, and the site's old address sends them there too.",
  "domain.done": "Done: the site is at {address}.",
  "domain.check": "Check again",
  "domain.checking": "Checking…",
  "domain.checkFailed": "Couldn't check the records just now. Try again in a moment.",
  "domain.remove": "Remove domain",
  "domain.removeTitle": "Remove {domain}?",
  "domain.removeBody":
    "The site goes back to its address on {host}. Delete the records at your registrar afterwards, so nobody else can use the domain for a site.",
  "domain.removeMessage": "Stop using the domain {domain}",
  "domain.error.not-allowed":
    "Your account can't change the site's {host} Pages settings. Ask one of the site's owners to make you an owner too, or to connect the domain for you.",
  "domain.error.taken": "Another site on {host} already uses this domain. If it's yours too, remove it there first.",
  "domain.error.invalid": "{host} doesn't accept this domain.",
  "domain.error.not-ready": "The HTTPS certificate isn't ready yet. Try again in a while.",
  "domain.error.other": "Something went wrong.",
  "owner.token.title": "Use an owner token",
  "owner.token.intro":
    "Inviting and removing editors, and connecting a domain, need more access on {host} than signing in has. Create a second token for them. It's kept only until you close this tab, and stops working after a day; you can delete it on {host} sooner.",
  "owner.token.create": "Create an owner token on {host}",
  "owner.token.chooseSite": "If {host} asks what the token can access, choose only this site.",
  "owner.token.paste": "Copy the token and paste it here:",
  "owner.token.label": "Owner token",
  "owner.token.use": "Use this token",
  "owner.token.checking": "Checking…",
  "owner.token.error":
    "That token can't manage this site. Check that it was made by one of the site's owners, that it can access this site, and that the whole token was copied.",
  "owner.token.active": "This tab is using an owner token.",
  "owner.token.forget": "Stop using it",

  "settings.tab.editors": "Editors",
  "settings.tab.updates": "Updates",
  "updates.intro":
    "Goodfellow, the software the site runs on, gets fixes and new releases. Fixes install on their own each night, and only once the site has been checked to still build with them.",
  "updates.local": "Updates are shown in the published site's admin panel, where you sign in with GitHub or GitLab.",
  "updates.demo": "Updates aren't installed in a demo.",
  "updates.loading": "Checking for updates…",
  "updates.current": "This site uses Goodfellow {version}.",
  "updates.unknownVersion": "This site's Goodfellow release couldn't be found.",
  "updates.missing":
    "This site's build setup doesn't install updates on its own, for example because it was made before it could, or because it's published with Vercel. A developer can add it, as the documentation explains.",
  "updates.needsSetup":
    "Automatic updates aren't turned on yet. They need {host} to let the site's build publish the update, and to run it each night.",
  "updates.enable": "Turn on automatic updates",
  "updates.fixes.title": "Fixes",
  "updates.fixes.ready":
    "Fixes up to Goodfellow {version} are ready. They install on their own tonight, or you can install them now.",
  "updates.fixes.readyPaused":
    "Fixes up to Goodfellow {version} are ready. Automatic fixes are turned off, so they're only installed if you install them now.",
  "updates.fixes.now": "Install fixes now",
  "updates.fixes.none": "The site has every fix for its release.",
  "updates.newer.title": "Goodfellow {version} is out",
  "updates.newer.body":
    "Newer releases can change how some things work, so they're only installed when one of the site's owners chooses to. Read what's new first.",
  "updates.newer.whatsNew": "What's new",
  "updates.newer.install": "Update to {version}",
  "updates.newer.onlyOwners": "Only the site's owners can install a newer release.",
  "updates.automatic.label": "Install fixes automatically each night",
  "updates.automatic.hint":
    "Turn this off to keep the site on the release it has now, for example while something an update changed is looked into. Fixes are then only installed when someone installs them here.",
  "updates.automatic.onlyOwners": "Only the site's owners can change this.",
  "updates.automatic.turnOff": "Turn off automatic fixes",
  "updates.automatic.turnOn": "Turn on automatic fixes",
  "updates.back.title": "Something stopped working?",
  "updates.back.body":
    "If something stopped working when Goodfellow {current} was installed, you can go back to {version}. The site is checked to still build with it first. Updates won't install {current} again, but will install fixes that come after it.",
  "updates.back.button": "Go back to {version}",
  "updates.back.confirm": "Go back to Goodfellow {version}? It takes a few minutes.",
  "updates.skipped.title": "Releases that won't be installed",
  "updates.skipped.body": "The site went back from these releases, so updates don't install them.",
  "updates.skipped.allow": "Allow {version} again",
  "updates.skipped.allowMessage": "Allow Goodfellow {version} again",
  "updates.started": "The update has started. It takes a few minutes, and this page shows how it went.",
  "updates.last.title": "Last update",
  "updates.last.none": "No update has run yet.",
  "updates.last.running": "An update is running now. It takes a few minutes.",
  "updates.last.updated": "On {date}, Goodfellow {version} was installed.",
  "updates.last.updatedSome": "On {date}, an update was installed.",
  "updates.last.wentBack": "On {date}, the site went back to Goodfellow {version}.",
  "updates.last.paused": "On {date}, automatic fixes were turned off, so nothing was installed.",
  "updates.last.upToDate": "On {date}, there was nothing new to install.",
  "updates.last.failed": "On {date}, the update didn't work, so nothing changed and the site stayed as it was.",
  "updates.last.unknown": "An update ran on {date}.",
  "updates.last.details": "See the details on {host}",
  "updates.failed.build":
    "The site didn't build with Goodfellow {version}; a developer may need to look at the details.",
  "updates.failed.install": "Its packages couldn't be installed. The next night tries again.",
  "updates.failed.blocks": "One of the site's blocks couldn't be updated.",
  "updates.failed.publish": "Someone published at the same time. The next night tries again.",
  "updates.kept":
    "Someone changed these files of the site's blocks, so the update left them as they were. A developer can compare them with the new versions:",
  "updates.error.load": "The updates couldn't be checked. Check your connection and try again.",
  "updates.error.not-allowed": "Your account can't do that on {host}. Ask one of the site's owners.",
  "updates.error.missing": "This site's build setup doesn't install updates, so there's nothing to run.",
  "updates.error.save": "The change couldn't be saved. Try again in a moment.",
  "updates.error.other": "Something went wrong. Try again in a moment.",
  "editors.intro": "The people who can edit this site.",
  "editors.roles":
    "Editors can change and publish everything in the admin panel. Owners can also invite and remove editors, and connect a domain.",
  "editors.local": "Editors are invited in the published site's admin panel, where you sign in with GitHub or GitLab.",
  "editors.demo": "Editors can't be invited in a demo.",
  "editors.loading": "Loading editors…",
  "editors.onlyOwners": "Only the site's owners can invite and remove editors.",
  "editors.cantPublish":
    "Editors can't publish yet: {host} only lets owners publish to the site until it's told to let editors publish too.",
  "editors.letPublish": "Let editors publish",
  "editors.person": "Person",
  "editors.role": "Can",
  "editors.roleFor": "What {name} can do",
  "editors.actions": "Actions",
  "editors.role.owner": "Owner",
  "editors.role.editor": "Editor",
  "editors.role.viewer": "Can't publish",
  "editors.you": "You",
  "editors.invited": "Invited, hasn't accepted yet",
  "editors.inherited": "Through a group on {host}",
  "editors.remove": "Remove",
  "editors.withdraw": "Withdraw invitation",
  "editors.removeTitle": "Remove {name}?",
  "editors.removeBody": "They won't be able to edit the site any more. Their account on {host} stays as it is.",
  "editors.withdrawTitle": "Withdraw the invitation to {name}?",
  "editors.withdrawBody": "The invitation stops working. You can invite them again later.",
  "editors.invite.title": "Invite someone",
  "editors.invite.field": "Their {host} username",
  "editors.invite.hint":
    "They need a {host} account. {host} emails them an invitation, which they accept before they can sign in here.",
  "editors.invite.fieldEmail": "Their email address or {host} username",
  "editors.invite.hintEmail":
    "With an email address, {host} emails them an invitation, and they make an account if they don't have one.",
  "editors.invite.submit": "Invite",
  "editors.error.load": "The editors couldn't be loaded. Check your connection and try again.",
  "editors.error.not-allowed": "You can't change who edits the site.",
  "editors.error.not-found": "There's no {host} account with that name. Check the spelling.",
  "editors.error.invalid": "That isn't a username or email address that {host} accepts.",
  "editors.error.already": "They already edit the site, or have been invited.",
  "editors.error.other": "Something went wrong. Try again in a moment.",
  "general.siteTitle": "Site name",
  "general.description": "Description",
  "general.descriptionHint": "Shown by search engines when a page doesn't have its own description.",
  "general.url": "Site address",
  "general.urlHint": "The full public address, such as https://example.org. Used for search engines and link previews.",
  "general.externalLinksInNewTab": "Open links to other sites in a new tab",
  "general.externalLinksInNewTabHint":
    "Applies to every link to another site: menus, buttons and text. Links to this site's own pages open in the same tab.",
  "general.language": "Language code",
  "general.languageHint": "Such as en, es or fr.",
  "general.timeZone": "Time zone",
  "general.timeZoneHint":
    "The time zone events' times are in. Calendars show them in it, and visitors' calendars move them to their own.",
  "general.timeZoneNone": "Not set: times are shown as they're written",
  "general.timeZoneUseMine": "Use {zone}",
  "general.titleTemplate": "Browser tab title",
  "general.titleTemplateHint": '%s is replaced by the page title, so "%s | My site" shows "About | My site".',
  "general.favicon": "Browser tab icon",
  "general.logo": "Logo",
  "general.logoAlt": "Logo description",
  "general.socialImage": "Image when shared on social media",
  "general.contact": "Contact details",
  "general.contactHint": "Shown wherever a Contact details block is placed, such as the footer.",
  "general.address": "Address",
  "general.phone": "Phone",
  "general.email": "Email",

  "theme.colors": "Colors",
  "theme.fonts": "Fonts",
  "theme.fontsHint": "Choose from Google Fonts. Site default uses each visitor's standard font.",
  "font.default": "Site default",
  "font.defaultHint": "Visitor's standard font",
  "font.search": "Search fonts",
  "font.searchHint": "Type to search Google Fonts, then use the arrow keys and Enter to choose.",
  "font.loading": "Loading fonts…",
  "font.noMatch": "No fonts match “{query}”.",
  "font.category.sans-serif": "Sans serif",
  "font.category.serif": "Serif",
  "font.category.display": "Display",
  "font.category.handwriting": "Handwriting",
  "font.category.monospace": "Monospace",
  "theme.headingFont": "Headings",
  "theme.bodyFont": "Text",
  "theme.radius": "Corner rounding",
  "theme.radiusHint": "Such as 0.5rem, or 0 for square corners.",
  "theme.color.background": "Background",
  "theme.color.foreground": "Text",
  "theme.color.primary": "Main color",
  "theme.color.primaryForeground": "Text on main color",
  "theme.color.secondary": "Second color",
  "theme.color.secondaryForeground": "Text on second color",
  "theme.color.muted": "Subtle background",
  "theme.color.mutedForeground": "Subtle text",
  "theme.color.accent": "Highlight",
  "theme.color.accentForeground": "Text on highlight",
  "theme.color.border": "Borders",
  "theme.default": "Default",
  "theme.pickColor": "Choose a color for {name}",

  "menus.intro": "Menus are lists of links. Show one anywhere with the Menu block, using its name.",
  "menus.empty": "There are no menus yet.",
  "menus.add": "Add menu",
  "menus.newName": "New menu name",
  "menus.nameInvalid": "Use lowercase letters, numbers and hyphens, and a name no other menu uses.",
  "menus.deleteMenu": "Delete menu",
  "menus.addLink": "Add link",
  "menus.addSublink": "Add link below this one",
  "menus.label": "Label",
  "menus.href": "Link to",
  "menus.moveUp": "Move up",
  "menus.moveDown": "Move down",
  "menus.remove": "Remove",
  "menus.newLink": "New link",

  "css.intro": "CSS here applies to every page and overrides the blocks' own styles. Tailwind's @apply works too.",
  "css.label": "Custom CSS",
  "code.editorHint":
    "Tab indents, and suggestions appear as you type. Press Escape, then Tab, to leave the editor. Ctrl+F finds and replaces.",
  "code.intro":
    "Code from services such as analytics or site verification, added to every page of the site. It never runs in the admin panel, so check it on the site once it's published. Paste only code you trust: it can change anything on the site.",
  "code.head": "In the page head",
  "code.headHint": "Script, style, link, meta and noscript tags, such as the ones Google Analytics gives you.",
  "code.body": "At the end of the page",
  "code.bodyHint": "Any HTML, such as a chat widget, added just before the end of every page.",
  "code.error.text":
    'The code in the page head has text outside a tag: "{text}". Only tags such as <script> and <meta> can go there.',
  "code.error.tag": 'A <{tag}> tag can\'t go in the page head. Put it in "At the end of the page" instead.',
  "code.error.unclosed": "A {tag} tag in the page head isn't closed.",
} as const;

export type StringKey = keyof typeof defaultStrings;
export type Strings = Record<StringKey, string>;

const StringsContext = createContext<Strings>(defaultStrings);

export function StringsProvider({ strings, children }: { strings?: Partial<Strings>; children: ReactNode }) {
  const value = useMemo(() => ({ ...defaultStrings, ...strings }), [strings]);
  return <StringsContext.Provider value={value}>{children}</StringsContext.Provider>;
}

export type Translate = (key: StringKey, values?: Record<string, string>) => string;

/** Returns `t(key, values)`, which looks up a string and fills in its `{placeholders}`. */
export function useStrings(): Translate {
  const strings = useContext(StringsContext);
  return (key, values) => strings[key].replace(/\{(\w+)\}/g, (match, name: string) => values?.[name] ?? match);
}
